### ISSUE TITLE
make_mine script doesn't work

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-scripts#1]
- [x] only create a correct new mine when it run directly in the intermine-scripts folder. If I use for example intermine-scripts/make_mine mymine I got an error Can't stat skeletons/mine: No such file or directory.

- [ ] If I switch to the intermine-scripts folder and run ./make_mine ../mymine the command works but sets properties e.g. mineName = "../mymine" in the buils.gradle file wrong.

- [x] gradlew permissions wrong

- [x] update skeletonks directory with the latest changes (for instance dbmodel/build.gradle is outdated)

**Comment by julie-sullivan** [comment]
Yes, sorry, I haven't updated the make mine or the make sources scripts. It's on my TODO list!

**Comment by julie-sullivan** [comment]
Detect if the current directory already has a `settings.gradle` file. If it's not there already, create a project.

**Comment by julie-sullivan** [comment]
This needs testing:

**make_mine**

- [ ] different directory locations (`/scripts`, `/home`, `/tmp` etc). Absolute and relative paths to script.
- [ ] All files keep their mode, specifically `gradlew` is executable. 
- [ ] mine can be deployed

**make_source**

- [ ] different directory locations (cwd, home directory, /tmp directory etc)
- [ ] `gradlew` is executable
- [ ] works if you do already have a gradle bio-sources project, or not.
- [ ] different source types can be installed. Custom, db and GFF data sources use a different skeleton to OBO and XML. Test both!

**Comment by julie-sullivan** [comment]
working as expected.
